name: Push-to-EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.233.120.6
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY}}
          port: 22
          script: |
            cd Learning-CI-CD
            ls
            git pull
            ls
            npm install
            npm run build
            npm run start